language: ruby
cache: bundle

rvm:
  - jruby
  - 2.0.0
  - 2.2.1
  - rbx

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - amos@binarynoggin.com
    on_failure: change
    on_success: never
